### ISSUE TITLE
有没有兄弟遇到重启丢配置的问题

### ISSUE THREAD

**Issue by WayneShao** [jingleijack/XIAOMI_AX3600#1]

**Comment by taonanshi** [comment]
没扩分区，ubi太大还没机会刷

**Comment by WayneShao** [comment]
> 没扩分区，ubi太大还没机会刷

我找到原因啦，是我之前用官方版系统的时候，开启ssh，然后用fuckax3600(其实我不知道这是一个具体什么软件)做了固化，没想到各种刷机之后，固化还有效，就像上了一个强力贞操带，后续的几次刷包其实都没有成功，我昨天重新把这个软件丢进去，unlock了一下，就一切正常了。
